plugins {
    id 'java'
    id 'jacoco'
    id 'application'
}

group = 'ru.nsu.blackjack'
version = '1.0-SNAPSHOT'

application {
    mainClass = 'ru.nsu.blackjack.Main'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
    finalizedBy 'jacocoTestReport'
}

jacocoTestReport {
    dependsOn test
}

run {
    standardInput = System.in
}